import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b0714",
        surface: "#151218",
        "surface-dim": "#151218",
        "surface-bright": "#3b383f",
        "surface-container-lowest": "#100d13",
        "surface-container-low": "#1d1a21",
        "surface-container": "#211e25",
        "surface-container-high": "#2c292f",
        "surface-container-highest": "#37333a",
        "on-surface": "#e7e0e9",
        "on-surface-variant": "#ccc3d3",
        "inverse-surface": "#e7e0e9",
        "inverse-on-surface": "#332f36",
        outline: "#968e9c",
        "outline-variant": "#4a4451",
        primary: "#d6baff",
        "on-primary": "#41127b",
        "primary-container": "#bf95ff",
        "on-primary-container": "#4f258a",
        "primary-fixed": "#ecdcff",
        "primary-fixed-dim": "#d6baff",
        "on-primary-fixed": "#280056",
        "on-primary-fixed-variant": "#582f93",
        "inverse-primary": "#7149ad",
        secondary: "#bdc4ee",
        "on-secondary": "#272e50",
        "secondary-container": "#40476a",
        "on-secondary-container": "#afb6df",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#bdc4ee",
        "on-secondary-fixed": "#111939",
        "on-secondary-fixed-variant": "#3d4567",
        tertiary: "#cfcc41",
        "on-tertiary": "#333200",
        "tertiary-container": "#b1ae23",
        "on-tertiary-container": "#414000",
        "tertiary-fixed": "#ece85b",
        "tertiary-fixed-dim": "#cfcc41",
        "on-tertiary-fixed": "#1d1d00",
        "on-tertiary-fixed-variant": "#4a4900",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        success: "#7dd8a3",
        "success-container": "#0f3d24",
        warning: "#f0c25d",
        "warning-container": "#4a3a0c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-mono": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      boxShadow: {
        card: "0px 4px 12px rgba(0,0,0,0.3)",
      },
      maxWidth: {
        page: "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
